version: '3'
services:
  
  telegraf:
    image: telegraf
    container_name: my-telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: always
    networks:
      - mynetwork

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydatabase
    restart: always
    networks:
      - mynetwork



networks:
  mynetwork:
    external: true