

version: '3'

services:
  my-graphite:
    image: graphiteapp/graphite-statsd
    container_name: my-graphite
    restart: always
    ports:
      - "8077:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      # - "8080:8080"
